name: maestro

services:
  maestro-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maestro-web
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - ea-ingress
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:80"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      kuma.maestro.group.name: "maestro"
      kuma.maestro-web.http.name: "website"
      kuma.maestro-web.http.parent_name: "maestro"
      kuma.maestro-web.http.url: "https://maestro.atbas.xyz"

networks:
  ea-ingress:
    external: true
